# Daybreak: statistics you can read.
#
# Fifty-three methods, each returning the same shaped record, each described
# twice: once for a reader who knows what a confidence interval is and once for
# a reader who does not. The two readings come from the same numbers and are
# generated by deterministic R code. No language model writes or alters a
# value anywhere in this application.
#
# The file layout follows the path a result takes. catalog.R describes the
# methods as data. data_io.R reads files. The three engine files compute.
# reporting.R and explanations.R write the two readings. plots.R draws.
# exports.R packages. ui_helpers.R and this file put it on screen.
# Copyright Abhik Roy. PolyForm Noncommercial License 1.0.0.

# RStudio's Run App button opens this file directly, so the dependency check
# belongs here as well as in the Finder launcher.
if (!isTRUE(getOption("daybreak.dependencies.checked"))) {
  source("install.R", chdir = TRUE)
}

options(shiny.maxRequestSize = 200 * 1024^2)

library(shiny)
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
library(scales)

source("R/version.R")
source("R/catalog.R")
source("R/data_io.R")
source("R/analysis_utils.R")
source("R/imputation.R")
source("R/engines_core.R")
source("R/engines_advanced.R")
source("R/engines_ml.R")
source("R/reporting.R")
source("R/explanations.R")
source("R/session_state.R")
source("R/local_models.R")
source("R/plots.R")
source("R/exports.R")
source("R/ui_helpers.R")

# Loaded before anything else so that the sidebar footer, the exports, and the
# report template all read the same release string.
app_name <- "Daybreak"

# Small header controls live here so the page layout below stays readable.
palette_button <- function(name, label, colors, pressed = FALSE) {
  tags$button(
    type = "button", class = "palette-option", `data-palette` = name,
    `aria-pressed` = tolower(as.character(pressed)),
    `aria-label` = paste("Use", label, "palette"),
    span(class = "swatches", lapply(colors[1:4], function(color) tags$i(style = sprintf("--swatch:%s", color)))),
    span(class = "palette-name", label)
  )
}

# Page shell: header, three-step sidebar, results, and dialogs.
# The page ------------------------------------------------------------------
#
# One screen, three steps down the left, the reading on the right. There are no
# hidden panels holding results, because a reader who has to find a tab to see
# whether their analysis worked will assume it did not.
ui <- fluidPage(
  tags$head(
    tags$title("Daybreak | Statistics you can read"),
    tags$meta(name = "description", content = "A private, local statistical workbench with plain-language reports and publication-ready figures."),
    tags$meta(name = "theme-color", content = "#0d141b"),
    tags$link(rel = "icon", type = "image/svg+xml", href = "icons/daybreak-icon-transparent.svg"),
    tags$link(rel = "stylesheet", type = "text/css", href = "app.css"),
    includeScript("www/app.js")
  ),
  tags$a(class = "skip-link", href = "#main-content", "Skip to results"),

  tags$header(class = "app-header",
    div(class = "brand", div(class = "brand-symbol", `aria-hidden` = "true"),
        span(class = "brand-name", "Daybreak"), span(class = "brand-tag", "statistics you can read")),
    div(class = "header-spacer"),
    div(class = "header-actions",
      div(class = "header-nav-group",
        tags$a(href = "#methods-panel", class = "header-button", role = "button",
               icon_svg("chart"), span(class = "header-text", "Methods")),
        tags$a(href = "#formats-panel", class = "header-button", role = "button",
               icon_svg("data"), span(class = "header-text", "Data formats")),
        tags$a(href = "#help-panel", class = "header-button", role = "button",
               icon_svg("help"), span(class = "header-text", "Help")),
        tags$a(href = "#models-panel", class = "header-button", role = "button",
               icon_svg("spark"), span(class = "header-text", "Local models")),
        tags$a(href = "#session-panel", class = "header-button", role = "button",
               icon_svg("save"), span(class = "header-text", "Session"))
      ),
      div(class = "header-display-group",
      div(class = "appearance-wrap",
        tags$button(id = "appearance-button", type = "button", class = "icon-button color-vision-button",
                    `aria-haspopup` = "true", `aria-expanded` = "false",
                    `aria-controls` = "appearance-panel",
                    `aria-label` = "Color vision settings", title = "Color vision settings",
                    icon_svg("vision")),
        div(id = "appearance-panel", class = "appearance-panel", role = "dialog",
          `aria-labelledby` = "appearance-title", `aria-hidden` = "true",
          div(class = "appearance-head", strong(id = "appearance-title", "Color vision settings"),
              tags$button(type = "button", class = "icon-button", `data-action` = "close-appearance", `aria-label` = "Close color vision settings", "×")),
          p(class = "palette-intro", "Choose a palette for charts and interface accents. Shape and line style continue to carry meaning."),
          div(class = "palette-options",
              palette_button("standard", "Standard color", DAYBREAK_PALETTES$standard, TRUE),
              palette_button("protanopia", "Protanopia", DAYBREAK_PALETTES$protanopia),
              palette_button("deuteranopia", "Deuteranopia", DAYBREAK_PALETTES$deuteranopia),
              palette_button("tritanopia", "Tritanopia", DAYBREAK_PALETTES$tritanopia),
              palette_button("monochrome", "Monochrome", DAYBREAK_PALETTES$monochrome))
        )
      ),
      tags$button(id = "theme-toggle", type = "button", class = "icon-button",
                  `aria-label` = "Switch to light mode",
                  span(class = "theme-icon theme-icon-sun", icon_svg("sun")),
                  span(class = "theme-icon theme-icon-moon", icon_svg("moon")))
      )
    )
  ),

  div(class = "app-shell",
    tags$aside(class = "sidebar", `aria-label` = "Analysis controls",
      div(class = "workflow-stack",
      tags$details(id = "workflow-step-1", class = "workflow-card", open = "open",
        tags$summary(div(class = "workflow-summary-main", span(class = "step-number", "1"),
                         div(strong("Choose data"), uiOutput("workflow_data_state"))),
                     span(class = "workflow-chevron", "⌄")),
        div(class = "workflow-card-body",
        div(class = "source-choice-card",
          div(class = "source-choice-label", "Your data"),
          fileInput("upload_file", "Data file", accept = paste0(".", SUPPORTED_EXTENSIONS),
                    buttonLabel = "Choose file", placeholder = "No file selected"),
          uiOutput("sheet_control"),
          tags$details(class = "advanced-box",
            tags$summary("Text-file settings"),
            div(class = "advanced-body",
                selectInput("delimiter", "Delimiter",
                            c("Detect automatically" = "auto", "Comma" = ",", "Tab" = "\t", "Semicolon" = ";", "Pipe" = "|")),
                selectInput("decimal_mark", "Decimal mark", c("Period: 12.5" = ".", "Comma: 12,5" = ",")))
          ),
          div(class = "data-note", icon_svg("data"),
              span("CSV, TSV, Excel, LibreOffice ODS, SPSS, Stata, SAS, R, JSON, Parquet, and Feather files are accepted."))
        ),
        div(class = "source-divider", span("or")),
        div(class = "source-choice-card sample-source-card",
          div(class = "source-choice-label", "Built-in example"),
          selectInput("sample_id", "Example dataset", choices = sample_choices(), selected = "iris"),
          actionButton("load_sample", "Load this example", class = "load-sample-button"),
          uiOutput("sample_note")
        ),
        uiOutput("active_data_status")
      )),
      tags$details(id = "workflow-step-2", class = "workflow-card",
        tags$summary(div(class = "workflow-summary-main", span(class = "step-number", "2"),
                         div(strong("Choose a method"), uiOutput("workflow_method_state"))),
                     span(class = "workflow-chevron", "⌄")),
        div(id = "method-control", class = "workflow-card-body",
        selectInput("method", label = "Method", choices = analysis_choices(),
                    selected = "descriptives", selectize = FALSE),
        uiOutput("method_fit_note"),
        tags$a(href = "#methods-panel", class = "browse-method-button btn", role = "button",
               icon_svg("chart"), "Browse methods by question"),
        tags$button(type = "button", class = "workflow-next-button", `data-open-step` = "3", "Continue to columns")
      )),
      tags$details(id = "workflow-step-3", class = "workflow-card",
        tags$summary(div(class = "workflow-summary-main", span(class = "step-number", "3"),
                         div(strong("Assign columns"), span(class = "workflow-state", "Choose the roles for this method"))),
                     span(class = "workflow-chevron", "⌄")),
        div(class = "workflow-card-body", uiOutput("role_controls"), uiOutput("analysis_options"),
            actionButton("run_analysis", "Run the analysis", class = "run-button",
                         `data-shortcut` = "\u2318\u21a9"),
            p(class = "sidebar-run-hint", "Command and Return, or Control and Return, runs it from anywhere on the page."))
      )),
      uiOutput("session_status"),
      div(class = "sidebar-foot", HTML(paste0(
        app_name, " ", DAYBREAK_VERSION, ". Built with ",
        '<a href="https://www.r-project.org" target="_blank" rel="noopener">R</a> and ',
        '<a href="https://shiny.posit.co" target="_blank" rel="noopener">Shiny</a>. ',
        "Copyright Abhik Roy, released under the ",
        '<a href="https://polyformproject.org/licenses/noncommercial/1.0.0" ',
        'target="_blank" rel="noopener">PolyForm Noncommercial License 1.0.0</a>.')))
    ),

    tags$main(id = "main-content", class = "main-stage", tabindex = "-1",
      div(class = "main-inner", uiOutput("landing_visibility_style"),
          div(class = "working-bar", `aria-hidden` = "true"),
          div(id = "landing-page", landing_page_ui()),
          uiOutput("data_summary"), uiOutput("data_preview_inline"),
          uiOutput("method_summary"), uiOutput("main_results"))
    )
  ),

  static_dialog_ui("methods-panel", "Choose a method", methods_directory_ui()),
  static_dialog_ui("formats-panel", "Data formats", data_formats_ui()),
  static_dialog_ui("help-panel", "Help with Daybreak", help_ui()),
  static_dialog_ui("models-panel", "Local language models", local_models_ui()),
  static_dialog_ui("session-panel", "Save or open a session", session_file_ui()),
  static_dialog_ui("imputation-panel", "Missing-data workspace", imputation_ui()),
  div(id = "connection-warning", class = "connection-warning", role = "alert",
      "The R session disconnected. Return to R, read the console message, and restart Daybreak.")
)

# The server ----------------------------------------------------------------
#
# State lives in one reactiveValues list rather than in several reactives that
# depend on each other. Loading data, preparing a working copy, running an
# analysis, and opening a session all write to the same place, so there is
# exactly one answer to what is currently on screen.
server <- function(input, output, session) {
  # The active data and the latest result travel together through the app.
  state <- reactiveValues(
    result = NULL,
    narrative = NULL,
    accessible = NULL,
    model_text = NULL,
    model_error = NULL,
    model_name = NULL,
    data = NULL,
    data_name = NULL,
    data_source = "upload",
    sample_id = NULL,
    original_data = NULL,
    original_data_name = NULL,
    imputation_model = NULL,
    imputation_label = NULL,
    imputation_columns = character(0),
    imputation_filled = 0L,
    roles = NULL,
    options = NULL,
    pending_roles = NULL,
    pending_options = NULL,
    restoring_session = FALSE,
    restore_waiting_for_method = FALSE,
    session_message = NULL,
    error = NULL,
    ollama = list(ok = FALSE, models = character(0), message = "Checking Ollama on this Mac."),
    model_pull = NULL,
    model_pull_name = NULL,
    model_pull_log = character(0),
    model_pull_status = NULL,
    model_test = NULL
  )

  # A changed method or dataset must never leave an old answer on screen.
  clear_result_state <- function() {
    state$result <- NULL
    state$narrative <- NULL
    state$accessible <- NULL
    state$model_text <- NULL
    state$model_error <- NULL
    state$model_name <- NULL
    state$roles <- NULL
    state$options <- NULL
    state$error <- NULL
  }

  current_role_values <- function(method_id) {
    spec <- ANALYSES[[method_id]]
    values <- lapply(spec$roles, function(item) {
      input[[item$id]] %||% if (grepl("many|predictors", item$type)) character(0) else ""
    })
    stats::setNames(values, vapply(spec$roles, `[[`, character(1), "id"))
  }

  restore_option_inputs <- function(values) {
    if (!length(values)) return(invisible(NULL))
    checkbox_ids <- c("equal_var", "continuity_correction", "factor_interaction", "reml", "growth_random_slope")
    slider_ids <- c("conf_level", "train_fraction", "elastic_alpha")
    selectize_ids <- c("ordered", "ordinal_order")
    select_ids <- c("cor_method", "rotation", "factor_method", "estimator", "missing_method")
    for (id in names(values)) {
      value <- values[[id]]
      if (is.null(value)) next
      if (id %in% checkbox_ids) updateCheckboxInput(session, id, value = isTRUE(value))
      else if (id %in% slider_ids) updateSliderInput(session, id, value = value)
      else if (id %in% selectize_ids) updateSelectizeInput(session, id, selected = value)
      else if (id %in% select_ids) updateSelectInput(session, id, selected = value)
      else updateNumericInput(session, id, value = value)
    }
    invisible(NULL)
  }

  method_feasibility_message <- function(data = state$data) {
    if (is.null(data)) return(list(items = list()))
    fits <- catalog_feasibility(data)
    list(items = unname(lapply(names(fits), function(id) {
      list(id = id, possible = isTRUE(fits[[id]]$possible), reason = fits[[id]]$reason)
    })))
  }

  send_method_feasibility <- function(data = state$data) {
    message <- method_feasibility_message(data)
    session$onFlushed(function() {
      session$sendCustomMessage("method-feasibility", message)
    }, once = TRUE)
    invisible(message)
  }

  load_data_state <- function(data, name, source, sample_id = NULL) {
    state$data <- data
    state$data_name <- name
    state$data_source <- source
    state$sample_id <- sample_id
    state$original_data <- NULL
    state$original_data_name <- NULL
    state$imputation_model <- NULL
    state$imputation_label <- NULL
    state$imputation_columns <- character(0)
    state$imputation_filled <- 0L
    state$pending_roles <- NULL
    state$pending_options <- NULL
    state$restoring_session <- FALSE
    state$restore_waiting_for_method <- FALSE
    clear_result_state()
    session$sendCustomMessage("landing-visibility", list(show = FALSE))
    session$sendCustomMessage("workflow-progress", list(step = 2))
    send_method_feasibility(data)
    invisible(data)
  }

  # This rule comes from reactive state, so it cannot be missed while the
  # browser is still registering message handlers.
  output$landing_visibility_style <- renderUI({
    if (is.null(state$data)) return(NULL)
    tags$style(id = "landing-data-rule", HTML("#landing-page{display:none!important;}"))
  })

  output$workflow_data_state <- renderUI({
    if (is.null(state$data)) return(span(class = "workflow-state", "Upload a file or open an example"))
    span(class = "workflow-state is-complete", state$data_name)
  })

  output$workflow_method_state <- renderUI({
    method_id <- input$method %||% "descriptives"
    span(class = "workflow-state", ANALYSES[[method_id]]$name)
  })

  output$method_fit_note <- renderUI({
    req(state$data)
    method_id <- input$method %||% "descriptives"
    fit <- method_feasibility(ANALYSES[[method_id]], state$data)
    div(
      class = paste("method-fit-note", if (fit$possible) "is-likely" else "is-unlikely"),
      icon_svg(if (fit$possible) "check" else "help"),
      span(if (fit$possible) fit$reason else paste(fit$reason, "You can still run it."))
    )
  })

  output$session_status <- renderUI({
    div(class = "session-status connected", span(class = "session-dot"), "R session connected")
  })

  output$active_data_status <- renderUI({
    data <- state$data
    if (is.null(data)) return(NULL)
    div(
      class = "active-data-status", icon_svg("check"),
      div(
        strong(state$data_name),
        span(sprintf(
          "%s rows, %s columns, ready to analyze",
          format(nrow(data), big.mark = ","),
          format(ncol(data), big.mark = ",")
        ))
      )
    )
  })

  # Workbook sheet names are read separately from the data so that the sheet
  # selector can appear before anything is parsed. Reading a large workbook
  # twice is cheaper than making the reader guess which sheet they want.
  sheet_names <- reactive({
    req(input$upload_file)
    spreadsheet_sheets(input$upload_file$datapath, input$upload_file$name)
  })

  uploaded_data <- reactive({
    req(input$upload_file)
    sheets <- sheet_names()
    selected_sheet <- if (length(sheets)) input$sheet %||% sheets[1] else NULL
    data <- read_uploaded_data(
      input$upload_file$datapath, input$upload_file$name, sheet = selected_sheet,
      delimiter = input$delimiter %||% "auto", decimal = input$decimal_mark %||% "."
    )
    list(data = data, name = input$upload_file$name)
  })

  # Data can come from a local file or one of the built-in examples.
  observeEvent(uploaded_data(), {
    payload <- uploaded_data()
    load_data_state(payload$data, payload$name, source = "upload")
    showNotification(
      sprintf("%s is ready. Raw rows are now visible.", payload$name),
      type = "message", duration = 4
    )
  }, ignoreInit = FALSE)

  # Loading a sample also sets its starting method and preselects the roles, so
  # the reader can press Run immediately. Anyone can then change any of it.
  # A quick-start card carries the sample name. Loading it, choosing its
  # starting method, and running the analysis happen in one press, because the
  # point of the card is that a first-time reader sees a finished result before
  # they have to learn what any of the controls do.
  observeEvent(input$quick_start_sample, {
    id <- input$quick_start_sample
    if (is.null(id) || !nzchar(id) || is.null(SAMPLES[[id]])) return()
    updateSelectInput(session, "sample_id", selected = id)
    data <- load_sample(id)
    load_data_state(data, SAMPLES[[id]]$name, "sample", id)
    method_id <- SAMPLES[[id]]$method %||% "descriptives"
    updateSelectInput(session, "method", selected = method_id)
    session$sendCustomMessage("landing-visibility", list(show = FALSE))
    # The role inputs are rebuilt by the method observer, so the run has to wait
    # for that pass to finish rather than firing against a half-built form.
    # later ships with Shiny, but the card still has to work if it is absent:
    # the sample and method are already chosen, so the reader only presses Run.
    if (requireNamespace("later", quietly = TRUE)) {
      later::later(function() session$sendCustomMessage("click-run", list()), 0.35)
    }
  }, ignoreInit = TRUE)

  observeEvent(input$load_sample, {
    id <- input$sample_id %||% "iris"
    payload <- list(data = load_sample(id), name = SAMPLES[[id]]$name, sample_id = id)
    recommended <- SAMPLES[[id]]$method
    updateSelectInput(session, "method", selected = recommended)
    load_data_state(payload$data, payload$name, source = "sample", sample_id = id)
    showNotification(
      sprintf("%s is ready. %s is selected as the starting method.", payload$name, ANALYSES[[recommended]]$name),
      type = "message", duration = 4
    )
  }, ignoreInit = TRUE)

  # Changing the method rebuilds the role inputs and preselects columns that
  # fit. Preserving a previous choice when it still fits keeps a reader from
  # losing their selections while they compare two methods on the same data.
  observeEvent(input$method, {
    if (isTRUE(state$restoring_session) && !is.null(state$pending_roles) &&
        identical(input$method, state$pending_roles$method_id)) {
      session$onFlushed(function() {
        restore_option_inputs(state$pending_options)
        state$restoring_session <- FALSE
        state$restore_waiting_for_method <- FALSE
      }, once = TRUE)
      return()
    }
    state$pending_roles <- NULL
    state$pending_options <- NULL
    clear_result_state()
  }, ignoreInit = TRUE)

  choose_method <- function(method_id, close_picker = FALSE) {
    if (!length(method_id) || !method_id %in% names(ANALYSES)) return(invisible(FALSE))
    updateSelectInput(session, "method", selected = method_id)
    if (isTRUE(close_picker)) removeModal()
    invisible(TRUE)
  }

  observeEvent(input$method_jump, {
    choose_method(input$method_jump)
  }, ignoreInit = TRUE)

  output$sample_note <- renderUI({
    id <- input$sample_id %||% "iris"
    info <- SAMPLES[[id]] %||% SAMPLES$iris
    tagList(
      div(class = "sample-note", info$note),
      div(class = "sample-starting-method", icon_svg("spark"),
          div(span("Starting method"), strong(ANALYSES[[info$method]]$name)))
    )
  })

  output$sheet_control <- renderUI({
    req(input$upload_file)
    sheets <- sheet_names()
    if (!length(sheets)) return(NULL)
    div(class = "sheet-wrap", selectInput("sheet", "Worksheet", choices = sheets, selected = sheets[1]))
  })

  output$data_summary <- renderUI({
    data <- state$data
    if (is.null(data)) return(NULL)
    sig <- data_signature(data)
    missing <- sum(is.na(data))
    div(id = "data-summary", class = "data-summary-strip",
        div(class = "data-summary-facts", icon_svg("data"),
            span(strong(state$data_name)),
            span(sprintf("%s rows", format(nrow(data), big.mark = ","))),
            span(sprintf("%s columns", format(ncol(data), big.mark = ","))),
            span(sprintf("%s numeric", length(sig$numeric))),
            span(sprintf("%s missing cells", format(missing, big.mark = ","))),
            if (!is.null(state$imputation_label)) span(class = "imputed-badge", state$imputation_label)),
        div(class = "data-summary-actions",
            if (missing > 0 || !is.null(state$imputation_label)) {
              tags$a(href = "#imputation-panel", class = "summary-action btn",
                     icon_svg("data"), if (is.null(state$imputation_label)) "Handle missing data" else "Missing-data workspace")
            },
            tags$a(href = "#data-preview", class = "summary-action btn",
                   icon_svg("table"), "View raw data")))
  })

  output$data_preview_inline <- renderUI({
    data <- state$data
    if (is.null(data)) return(NULL)
    shown <- min(nrow(data), 30L)
    tags$details(
      id = "data-preview", class = "inline-data-preview", open = if (is.null(state$result)) "open" else NULL,
      tags$summary(
        div(class = "inline-data-title", icon_svg("table"),
            span(strong("Raw data"), tags$small(sprintf("First %s of %s rows", shown, format(nrow(data), big.mark = ","))))),
        span(class = "inline-data-toggle", "Show or hide")
      ),
      div(class = "inline-data-body",
          table_ui(utils::head(data, shown)),
          div(class = "inline-data-footer",
              span("The download contains every row."),
              downloadButton("download_current_data", "Download full data as CSV", class = "download-btn compact-download")))
    )
  })

  output$method_summary <- renderUI({
    if (is.null(state$data)) return(NULL)
    method_summary_ui(input$method %||% "descriptives", compact = !is.null(state$result))
  })

  # Missing-data work happens on a copy; the loaded data stays available.
  output$imputation_controls <- renderUI({
    data <- state$data
    if (is.null(data)) return(div(class = "empty-table", "Load a file or example before opening this workspace."))
    missing_columns <- names(data)[vapply(data, anyNA, logical(1))]
    if (!length(missing_columns)) return(div(class = "empty-table", "The active data has no missing cells."))
    method <- input$imputation_method %||% "simple"
    tagList(
      selectizeInput("imputation_columns", "Columns to prepare", choices = names(data),
                     selected = missing_columns, multiple = TRUE,
                     options = list(plugins = list("remove_button"))),
      selectInput("imputation_method", "Method", c(
        "Median and most common category" = "simple",
        "Nearest neighbors (VIM)" = "knn",
        "Random forest (missForest)" = "missforest",
        "Multiple imputation by chained equations (mice)" = "mice"
      ), selected = method),
      if (method == "knn") numericInput("imputation_neighbors", "Number of neighbors", 5, min = 1, max = 50),
      if (method == "mice") div(class = "two-up",
        numericInput("imputation_count", "Completed datasets", 5, min = 2, max = 50),
        numericInput("imputation_iterations", "Iterations", 5, min = 1, max = 50)),
      if (method != "simple") numericInput("imputation_seed", "Random seed", 2026, min = 1, step = 1)
    )
  })

  # Filling missing values writes to a working copy and never to the loaded
  # data, so the reader can always return to the file as it arrived. The
  # analysis that follows carries a note saying the reported uncertainty does
  # not include uncertainty from the filling.
  observeEvent(input$run_imputation, {
    tryCatch({
      req(state$data)
      active_data <- state$data
      active_name <- state$data_name
      first_preparation <- is.null(state$original_data)
      prepared <- withProgress(message = "Preparing a working copy", value = 0.5, {
        impute_selected_data(
          state$data, input$imputation_columns %||% character(0), input$imputation_method %||% "simple",
          seed = input$imputation_seed %||% 2026L,
          imputations = input$imputation_count %||% 5L,
          iterations = input$imputation_iterations %||% 5L,
          neighbors = input$imputation_neighbors %||% 5L
        )
      })
      if (first_preparation) {
        state$original_data <- active_data
        state$original_data_name <- active_name
      }
      state$data <- prepared$data
      state$data_name <- paste0(state$original_data_name, " · working copy")
      state$imputation_model <- prepared$model
      state$imputation_label <- prepared$label
      state$imputation_columns <- prepared$columns
      state$imputation_filled <- prepared$filled
      clear_result_state()
      send_method_feasibility(state$data)
      showNotification(sprintf("The working copy filled %s cells.", format(prepared$filled, big.mark = ",")),
                       type = "message", duration = 5)
    }, error = function(e) {
      showNotification(conditionMessage(e), type = "error", duration = 10)
    })
  }, ignoreInit = TRUE)

  # Returning to the loaded file clears the working copy and the note attached
  # to results produced from it, so nothing on screen still refers to values
  # that are no longer in use.
  observeEvent(input$restore_original_data, {
    if (is.null(state$original_data)) {
      showNotification("No prepared working copy is active.", type = "message", duration = 4)
      return()
    }
    state$data <- state$original_data
    state$data_name <- state$original_data_name
    state$original_data <- NULL
    state$original_data_name <- NULL
    state$imputation_model <- NULL
    state$imputation_label <- NULL
    state$imputation_columns <- character(0)
    state$imputation_filled <- 0L
    clear_result_state()
    send_method_feasibility(state$data)
    showNotification("The originally loaded data is active again.", type = "message", duration = 4)
  }, ignoreInit = TRUE)

  output$imputation_status <- renderUI({
    if (is.null(state$imputation_label)) return(NULL)
    div(class = "imputation-status", icon_svg("check"),
        div(strong("Working copy active"),
            p(sprintf("%s filled %s cells across %s.", state$imputation_label,
                      format(state$imputation_filled, big.mark = ","),
                      paste(state$imputation_columns, collapse = ", ")))))
  })

  output$imputation_download <- renderUI({
    if (is.null(state$imputation_model) || !inherits(state$imputation_model, "mids")) return(NULL)
    tagList(downloadButton("download_imputation_object", "Download full MICE object", class = "download-btn"),
            p(class = "micro-note", "The RDS file contains every completed dataset and the information needed for pooled analysis in R."))
  })

  output$role_controls <- renderUI({
    data <- state$data
    req(data)
    method_id <- input$method %||% "descriptives"
    spec <- ANALYSES[[method_id]]
    sample_id <- if (identical(state$data_source, "sample")) state$sample_id else NULL
    defaults <- default_role_values(spec, data, sample_id = sample_id, method_id = method_id)
    restored <- if (!is.null(state$pending_roles) && identical(state$pending_roles$method_id, method_id)) state$pending_roles$values else NULL
    tagList(lapply(spec$roles, function(r) {
      current <- if (!is.null(restored) && !is.null(restored[[r$id]])) {
        restored[[r$id]]
      } else if (r$type == "lavaan_text") {
        default_sample_syntax(sample_id, method_id)
      } else {
        defaults[[r$id]]
      }
      role_input(r, data = data, current = current)
    }))
  })

  output$analysis_options <- renderUI({
    req(state$data)
    analysis_options_ui(input$method %||% "descriptives", state$data, ordinal_outcome = input$outcome %||% NULL)
  })

  # Session files carry the data and current choices in one RDS object.
  output$session_save_control <- renderUI({
    if (is.null(state$data)) {
      return(div(class = "session-save-empty", "Load a data file or built-in example before saving a session."))
    }
    downloadButton("download_session", "Save session (.daybreak.rds)", class = "download-btn session-download")
  })

  output$session_open_message <- renderUI({
    if (is.null(state$session_message)) return(NULL)
    div(class = paste("session-open-message", if (isTRUE(state$session_message$ok)) "is-ok" else "is-warning"),
        icon_svg(if (isTRUE(state$session_message$ok)) "check" else "help"),
        span(state$session_message$text))
  })

  # A session file is validated field by field before anything on screen
  # changes. A partially applied session would leave the reader looking at a
  # result that does not match the settings beside it.
  observeEvent(input$open_session, {
    state$session_message <- NULL
    tryCatch({
      req(input$session_file)
      saved <- read_daybreak_session(input$session_file$datapath)
      method_will_change <- !identical(isolate(input$method %||% "descriptives"), saved$method_id)
      state$restoring_session <- TRUE
      state$restore_waiting_for_method <- method_will_change
      state$data <- saved$data
      state$data_name <- saved$data_name %||% "Restored data"
      state$data_source <- saved$data_source %||% "session"
      state$sample_id <- saved$sample_id
      state$original_data <- saved$original_data
      state$original_data_name <- saved$original_data_name
      state$imputation_model <- NULL
      state$imputation_label <- saved$imputation_label
      state$imputation_columns <- saved$imputation_columns %||% character(0)
      state$imputation_filled <- saved$imputation_filled %||% 0L
      state$result <- saved$result
      state$narrative <- saved$narrative %||% (if (!is.null(saved$result)) build_narrative(saved$result) else NULL)
      state$accessible <- saved$accessible %||% (if (!is.null(saved$result)) build_accessible_explanation(saved$result) else NULL)
      state$model_text <- NULL
      state$model_error <- NULL
      state$model_name <- NULL
      state$error <- NULL
      state$roles <- saved$roles
      state$options <- saved$options
      state$pending_roles <- list(method_id = saved$method_id, values = saved$roles)
      state$pending_options <- saved$options
      updateSelectInput(session, "method", selected = saved$method_id)
      session$onFlushed(function() {
        if (!isTRUE(state$restore_waiting_for_method)) restore_option_inputs(saved$options)
        session$sendCustomMessage("restore-display", list(theme = saved$theme, palette = saved$palette))
        session$sendCustomMessage("landing-visibility", list(show = FALSE))
        session$sendCustomMessage("workflow-progress", list(step = 3))
        session$sendCustomMessage("close-static-dialog", list(id = "session-panel"))
        if (!isTRUE(state$restore_waiting_for_method)) state$restoring_session <- FALSE
      }, once = TRUE)
      send_method_feasibility(saved$data)
      state$session_message <- list(ok = TRUE, text = sprintf("Opened %s with %s rows and %s columns.", state$data_name, format(nrow(saved$data), big.mark = ","), format(ncol(saved$data), big.mark = ",")))
      showNotification("The saved Daybreak session is open.", type = "message", duration = 5)
    }, error = function(e) {
      state$restoring_session <- FALSE
      state$restore_waiting_for_method <- FALSE
      state$session_message <- list(ok = FALSE, text = conditionMessage(e))
      showNotification("Daybreak could not open that session. The Session panel explains why.", type = "warning", duration = 7)
    })
  }, ignoreInit = TRUE)

  # Keep the two explanations and the supporting result in one reading flow.
  output$main_results <- renderUI({
    data <- state$data
    if (is.null(data)) {
      return(NULL)
    }
    if (!is.null(state$error)) {
      return(analysis_error_ui(state$error))
    }
    if (is.null(state$result)) {
      return(suggestion_cards_ui(data))
    }
    result_tabs_ui(state$result, state$narrative, state$accessible, stale = settings_moved_on())
  })

  # The banner sits inside the result panel, so its button is a separate input.
  # Forwarding it keeps one run path rather than two copies of the same work.
  observeEvent(input$run_analysis_stale, {
    if (!is.null(input$run_analysis_stale) && input$run_analysis_stale > 0) {
      session$sendCustomMessage("click-run", list())
    }
  })

  # Recomputed whenever any part of the form moves. collect_roles stops when a
  # required role is empty, which is a normal state while the reader is still
  # choosing columns, so an incomplete form is simply not treated as stale.
  settings_moved_on <- reactive({
    if (is.null(state$result) || is.null(state$run_signature)) return(FALSE)
    method_id <- input$method %||% "descriptives"
    current <- tryCatch(
      analysis_signature(method_id, collect_roles(input, ANALYSES[[method_id]]), collect_options(input)),
      error = function(e) NULL
    )
    !is.null(current) && !identical(current, state$run_signature)
  })

  observeEvent(input$run_analysis, {
    method_id <- input$method %||% "descriptives"
    roles <- current_role_values(method_id)
    tryCatch({
      data <- state$data
      req(data)
      roles <- collect_roles(input, ANALYSES[[method_id]])
      opts <- collect_options(input)
      # Bootstrapped mediation, multilevel fits, and the resampling methods can
      # run for several seconds on a large file. Without a progress message the
      # only feedback was a button that had already returned to its normal
      # state, so the reader could not tell whether anything was happening.
      result <- withProgress(
        message = sprintf("Running %s", tolower(ANALYSES[[method_id]]$name)),
        detail = "Fitting the model and building the tables.",
        value = 0.45,
        run_analysis(method_id, data, roles, opts)
      )
      if (!is.null(state$imputation_label)) {
        note <- if (inherits(state$imputation_model, "mids")) {
          "This result uses the first completed MICE dataset. Inferential standard errors and intervals are not pooled across imputations; use the downloadable MICE object for a pooled analysis."
        } else {
          sprintf("This result uses a working copy prepared with %s. The displayed uncertainty does not include uncertainty from filling missing values.", tolower(state$imputation_label))
        }
        result$warnings <- unique(c(result$warnings, note))
      }
      narrative <- build_narrative(result)
      accessible <- build_accessible_explanation(result)
      state$data <- data
      state$result <- result
      state$narrative <- narrative
      state$accessible <- accessible
      state$model_text <- NULL
      state$model_error <- NULL
      state$model_name <- NULL
      state$roles <- roles
      state$options <- opts
      state$run_signature <- analysis_signature(method_id, roles, opts)
      state$error <- NULL
      session$sendCustomMessage("landing-visibility", list(show = FALSE))
      session$sendCustomMessage("scroll-main", list())
    }, error = function(e) {
      state$result <- NULL
      state$narrative <- NULL
      state$accessible <- NULL
      state$model_text <- NULL
      state$model_error <- NULL
      state$error <- plain_analysis_error(
        conditionMessage(e), method_id, roles = roles, data_name = state$data_name
      )
      showNotification(analysis_error_notification(state$error), type = "warning", duration = 12)
      session$sendCustomMessage("landing-visibility", list(show = FALSE))
      session$sendCustomMessage("scroll-main", list())
    })
  })

  output$main_plot <- renderPlot({
    req(state$result)
    analysis_plot(state$result, input$theme_mode %||% "dark", input$color_palette %||% "standard")
  }, res = 120, bg = "transparent")

  output$data_used_panel <- renderUI({
    req(state$result, state$data)
    tagList(
      h3("Column profile"), table_ui(column_profile(state$data)),
      h3("First 20 rows"), table_ui(utils::head(state$data, 20)),
      div(class = "data-note", icon_svg("data"), span(coverage_sentence(state$result)))
    )
  })

  # Ollama only receives finished explanation text, never the source rows.
  refresh_ollama <- function(notify = FALSE) {
    status <- ollama_list_models()
    state$ollama <- status
    choices <- local_model_choices(status$models)
    current <- isolate(input$local_model %||% "qwen3.5:4b")
    selected <- if (current %in% unname(choices)) current else unname(choices)[1]
    updateSelectInput(session, "local_model", choices = choices, selected = selected)
    if (isTRUE(notify)) showNotification(status$message, type = if (status$ok) "message" else "warning", duration = 5)
    invisible(status)
  }

  session$onFlushed(function() refresh_ollama(), once = TRUE)

  observeEvent(input$refresh_local_models, {
    refresh_ollama(notify = TRUE)
  }, ignoreInit = TRUE)

  output$ollama_status <- renderUI({
    status <- state$ollama
    div(class = paste("ollama-status", if (isTRUE(status$ok)) "is-ready" else "is-waiting"),
        span(class = "session-dot"), div(strong(if (isTRUE(status$ok)) "Ollama found" else "Ollama is not ready"), p(status$message)))
  })

  # Model downloads run through the Ollama command line rather than the HTTP
  # interface, because a pull can take several minutes and the command line
  # reports progress that can be shown to the reader.
  observeEvent(input$download_local_model, {
    model <- input$local_model %||% ""
    if (!valid_local_model_name(model)) {
      state$model_pull_status <- "Select a valid local model."
      return()
    }
    cli <- find_ollama_cli()
    if (!nzchar(cli)) {
      state$model_pull_status <- sprintf("Daybreak could not find the Ollama command. Open Terminal and run: ollama pull %s", model)
      return()
    }
    if (!requireNamespace("processx", quietly = TRUE)) {
      state$model_pull_status <- sprintf("Install the optional processx R package, or open Terminal and run: ollama pull %s", model)
      return()
    }
    if (!is.null(state$model_pull) && isTRUE(state$model_pull$is_alive())) {
      state$model_pull_status <- "A model download is already running."
      return()
    }
    pull <- ollama_pull_spec(model, cli)
    process <- try(processx::process$new(pull$command, pull$args, stdout = "|", stderr = "|", cleanup = TRUE), silent = TRUE)
    if (inherits(process, "try-error")) {
      state$model_pull_status <- "The model download could not start. Open Ollama and try again."
      return()
    }
    state$model_pull <- process
    state$model_pull_name <- model
    state$model_pull_log <- character(0)
    state$model_pull_status <- sprintf("Downloading %s. You can keep using Daybreak.", model)
  }, ignoreInit = TRUE)

  observe({
    process <- state$model_pull
    if (is.null(process)) return()
    invalidateLater(800, session)
    lines <- c(process$read_output_lines(), process$read_error_lines())
    lines <- trimws(lines[nzchar(trimws(lines))])
    if (length(lines)) {
      state$model_pull_log <- tail(c(state$model_pull_log, lines), 4)
      state$model_pull_status <- tail(lines, 1)
    }
    if (!process$is_alive()) {
      code <- process$get_exit_status()
      model <- state$model_pull_name
      state$model_pull <- NULL
      if (identical(code, 0L)) {
        state$model_pull_status <- sprintf("%s is installed and ready.", model)
        refresh_ollama()
      } else {
        state$model_pull_status <- sprintf("The %s download stopped with status %s. Open Ollama and try again.", model, code)
      }
    }
  })

  output$model_download_status <- renderUI({
    if (is.null(state$model_pull_status)) return(NULL)
    div(class = "model-download-status", icon_svg("download"),
        div(strong(state$model_pull_status),
            if (length(state$model_pull_log)) tags$small(paste(state$model_pull_log, collapse = "\n"))))
  })

  observeEvent(input$test_local_model, {
    model <- input$local_model %||% ""
    state$model_test <- NULL
    if (!valid_local_model_name(model)) {
      state$model_test <- list(ok = FALSE, message = "Select a valid local model first.")
      return()
    }
    answer <- withProgress(message = sprintf("Testing %s", model), detail = "The first response may take several minutes while the model loads.", value = 0.5, {
      ollama_generate("Reply with READY only.", model, timeout = 300)
    })
    if (!isTRUE(answer$ok)) {
      state$model_test <- list(ok = FALSE, message = answer$message)
      return()
    }
    preview <- substr(gsub("[\r\n]+", " ", trimws(answer$text)), 1, 90)
    state$model_test <- list(ok = TRUE, message = sprintf("%s loaded and answered: %s", model, preview))
    refresh_ollama()
  }, ignoreInit = TRUE)

  output$model_test_status <- renderUI({
    status <- state$model_test
    if (is.null(status)) return(NULL)
    div(class = paste("model-test-status", if (isTRUE(status$ok)) "is-ready" else "is-waiting"),
        icon_svg(if (isTRUE(status$ok)) "check" else "spark"),
        div(strong(if (isTRUE(status$ok)) "Model test passed" else "Model test needs attention"), p(status$message)))
  })

  # The restatement is compared against the source text digit by digit before
  # it is shown. A model that alters, adds, or drops a number has its answer
  # discarded and the original text stands.
  observeEvent(input$restate_local, {
    req(state$accessible)
    model <- input$local_model %||% "qwen3.5:4b"
    state$model_text <- NULL
    state$model_error <- NULL
    answer <- withProgress(
      message = "The local model is rewriting the explanation",
      detail = "The first reply can take several minutes while the model loads.",
      value = 0.5,
      {
        ollama_generate(build_local_model_prompt(state$accessible), model, timeout = 300)
      }
    )
    if (!isTRUE(answer$ok)) {
      state$model_error <- answer$message
      return()
    }
    # Structure and numbers are both checked. A rewrite that fails either is
    # discarded and the deterministic text stands.
    verdict <- check_local_rewrite(state$accessible, answer$text)
    if (!isTRUE(verdict$ok)) {
      state$model_error <- verdict$message
      return()
    }
    state$model_text <- answer$text
    state$model_name <- model
  }, ignoreInit = TRUE)

  output$local_restatement <- renderUI({
    if (!is.null(state$model_error)) {
      return(div(class = "local-restatement is-error", h3("Local rewrite not shown"), p(state$model_error)))
    }
    if (is.null(state$model_text)) return(NULL)
    # The rewrite comes back with the same five headings the everyday
    # explanation uses, so they are rendered as headings rather than folded into
    # paragraphs. Anything that is not one of the five is body text.
    lines <- trimws(strsplit(state$model_text, "\n", fixed = TRUE)[[1]])
    lines <- lines[nzchar(lines)]
    blocks <- lapply(lines, function(line) {
      bare <- toupper(gsub("[^A-Za-z ]", "", line))
      if (bare %in% LOCAL_MODEL_SECTIONS) {
        h4(class = "local-restatement-heading", tools::toTitleCase(tolower(bare)))
      } else {
        p(line)
      }
    })
    div(class = "local-restatement",
        div(class = "local-restatement-head", h3("Local model wording"), span(state$model_name)),
        blocks)
  })

  # Downloads are built from the data and result already shown on screen.
  output$download_current_data <- downloadHandler(
    filename = function() {
      stem <- tolower(gsub("[^A-Za-z0-9]+", "-", state$data_name %||% "daybreak-data"))
      paste0(gsub("(^-|-$)", "", stem), ".csv")
    },
    content = function(file) {
      req(state$data)
      utils::write.csv(state$data, file, row.names = FALSE, na = "")
    }
  )

  output$download_session <- downloadHandler(
    filename = function() daybreak_session_filename(),
    contentType = "application/x-r-rds",
    content = function(file) {
      req(state$data)
      method_id <- input$method %||% "descriptives"
      roles <- if (!is.null(state$result) && identical(state$result$method, method_id) && !is.null(state$roles)) state$roles else current_role_values(method_id)
      options <- if (!is.null(state$result) && identical(state$result$method, method_id) && !is.null(state$options)) state$options else collect_options(input)
      payload <- new_daybreak_session(
        data = state$data, data_name = state$data_name, data_source = state$data_source,
        sample_id = state$sample_id, method_id = method_id, roles = roles, options = options,
        result = if (!is.null(state$result) && identical(state$result$method, method_id)) state$result else NULL,
        narrative = if (!is.null(state$result) && identical(state$result$method, method_id)) state$narrative else NULL,
        accessible = if (!is.null(state$result) && identical(state$result$method, method_id)) state$accessible else NULL,
        original_data = state$original_data, original_data_name = state$original_data_name,
        imputation_label = state$imputation_label, imputation_columns = state$imputation_columns,
        imputation_filled = state$imputation_filled,
        theme = input$theme_mode %||% "dark", palette = input$color_palette %||% "standard"
      )
      write_daybreak_session(payload, file)
    }
  )

  output$download_imputation_object <- downloadHandler(
    filename = function() "daybreak-mice-imputations.rds",
    content = function(file) {
      req(state$imputation_model)
      saveRDS(state$imputation_model, file)
    }
  )

  output$download_plot <- downloadHandler(
    filename = function() paste0("daybreak-", input$method, ".", input$plot_format %||% "png"),
    content = function(file) {
      req(state$result)
      style <- plot_style(input$theme_mode %||% "dark", input$color_palette %||% "standard")
      plot <- analysis_plot(state$result, input$theme_mode %||% "dark", input$color_palette %||% "standard")
      export_plot(plot, file, input$plot_format %||% "png", input$plot_quality %||% "print",
                  input$plot_size %||% "standard", style$background)
    }
  )

  output$download_report <- downloadHandler(
    filename = function() paste0("daybreak-", input$method, ".", input$report_format %||% "html"),
    content = function(file) {
      req(state$result, state$narrative, state$accessible)
      write_report(state$result, state$narrative, file, input$report_format %||% "html", state$accessible)
    }
  )

  output$download_code <- downloadHandler(
    filename = function() paste0("daybreak-", input$method, "-reproduce.R"),
    content = function(file) {
      req(state$result)
      write_reproduction_script(state$result, file)
    }
  )

  output$download_bundle <- downloadHandler(
    filename = function() paste0("daybreak-", input$method, "-bundle.zip"),
    content = function(file) {
      req(state$result, state$narrative, state$accessible)
      plot <- analysis_plot(state$result, input$theme_mode %||% "dark", input$color_palette %||% "standard")
      write_analysis_bundle(state$result, state$narrative, plot, file,
                            input$theme_mode %||% "dark", input$color_palette %||% "standard", state$accessible)
    }
  )
}

shinyApp(ui, server)
